version: '3.9'
services:
  web:
    image: httpd:latest
    container_name: apache-web
    ports:
      - "8080:80"
    volumes:
      - ./www:/usr/local/apache2/htdocs/
    depends_on:
      - php

  php:
    image: php:8.1-fpm
    container_name: php-fpm
    volumes:
      - ./www:/var/www/html